### ISSUE TITLE
Media upload - Change storage

### ISSUE THREAD

**Issue by cmaneu** [surfriderfoundationeurope/po-mobile-backend#15]
**Subtasks**

- [ ] When uploading, the file destination container should change depending on the type of campaign
- [x] When uploading, add an entry into the Postgresql DB  `media` table
   - The 
- [ ] If it's an automatic trace, should copy the trace file with the video
    - There is folders
       - Mobile Automatic
       - Mobile Manuel
       - GoPro
