### ISSUE TITLE
Create a global API

### ISSUE THREAD

**Issue by cmaneu** [surfriderfoundationeurope/po-mobile-backend#29]
Todo: 

- [ ] Rename the project to something more global (both the GitHub project and VS project)
- [ ] Create Remote Dev Extension + Readme
- [ ] List API methods from LabelCV to port over
- [ ] Add OpenAPI Generation
- [ ] #25 Move settings to Key Vault.
